// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yukti.Infrastructure;

#nullable disable

namespace Yukti.Infrastructure.Migrations
{
    [DbContext(typeof(YuktiDbContext))]
    [Migration("20260816143352_AddTriggersTable")]
    partial class AddTriggersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Yukti.Domain.ApiTesting.ApiCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("api_collections", (string)null);
                });

            modelBuilder.Entity("Yukti.Domain.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("Yukti.Domain.Execution.FlowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variables");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "StartedAt");

                    b.ToTable("flow_runs", (string)null);
                });

            modelBuilder.Entity("Yukti.Domain.FlowAuthoring.Flow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("ContinueOnFailure")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeclaredVariables")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("declared_variables");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "FamilyId", "Version");

                    b.ToTable("flows", (string)null);
                });

            modelBuilder.Entity("Yukti.Domain.IdentityAccess.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Yukti.Domain.IdentityAccess.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsServiceAccount")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid[]>("RoleIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("role_ids");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Yukti.Domain.ModulePlugin.ModuleRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContractVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Trust")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("module_registrations", (string)null);
                });

            modelBuilder.Entity("Yukti.Domain.ProjectManagement.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Yukti.Domain.ProjectManagement.TestEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variables");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId");

                    b.ToTable("test_environments", (string)null);
                });

            modelBuilder.Entity("Yukti.Domain.Scheduling.TriggerDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CronExpression")
                        .HasColumnType("text");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastFiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RegisteredBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("WatchPath")
                        .HasColumnType("text");

                    b.Property<string>("WebhookPath")
                        .HasColumnType("text");

                    b.Property<string>("WebhookSecret")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("WebhookPath");

                    b.HasIndex("TenantId", "FlowId");

                    b.ToTable("triggers", (string)null);
                });

            modelBuilder.Entity("Yukti.Infrastructure.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FlowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("TenantId", "Key");

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("Yukti.Infrastructure.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Yukti.Infrastructure.ReadModels.FlowReportReadModel", b =>
                {
                    b.Property<Guid>("FlowRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("FinalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PassedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ProjectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("TotalDuration")
                        .HasColumnType("interval");

                    b.HasKey("FlowRunId");

                    b.HasIndex("TenantId");

                    b.ToTable("flow_reports", (string)null);
                });

            modelBuilder.Entity("Yukti.Infrastructure.ReadModels.TrendAggregateReadModel", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<double>("FlakeRateLast24h")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PassRateLast24h")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalRunsLast24h")
                        .HasColumnType("integer");

                    b.HasKey("TenantId");

                    b.ToTable("trend_aggregates", (string)null);
                });

            modelBuilder.Entity("Yukti.Domain.ApiTesting.ApiCollection", b =>
                {
                    b.OwnsMany("Yukti.Domain.ApiTesting.ApiRequest", "Requests", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ApiCollectionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Assertions")
                                .HasColumnType("jsonb")
                                .HasColumnName("assertions");

                            b1.Property<string>("Body")
                                .HasColumnType("jsonb")
                                .HasColumnName("body");

                            b1.Property<string>("Headers")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("headers");

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<string>("QueryParams")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("query_params");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("ApiCollectionId", "Order")
                                .IsUnique();

                            b1.ToTable("api_requests", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ApiCollectionId");
                        });

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Yukti.Domain.Execution.FlowRun", b =>
                {
                    b.OwnsMany("Yukti.Domain.Execution.StepResult", "Results", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AiAttribution")
                                .HasColumnType("jsonb")
                                .HasColumnName("ai_attribution");

                            b1.Property<string>("Data")
                                .HasColumnType("jsonb")
                                .HasColumnName("data");

                            b1.Property<TimeSpan>("Duration")
                                .HasColumnType("interval");

                            b1.Property<string>("Error")
                                .HasColumnType("text");

                            b1.Property<Guid>("FlowRunId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Message")
                                .HasColumnType("text");

                            b1.Property<string>("Module")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("SourceStepId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StepName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("FlowRunId");

                            b1.HasIndex("TenantId");

                            b1.ToTable("step_results", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FlowRunId");

                            b1.OwnsMany("Yukti.Domain.Execution.RetryAttempt", "RetryHistory", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("AttemptNumber")
                                        .HasColumnType("integer");

                                    b2.Property<DateTimeOffset>("AttemptedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<TimeSpan>("Duration")
                                        .HasColumnType("interval");

                                    b2.Property<string>("Error")
                                        .HasColumnType("text");

                                    b2.Property<string>("Status")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<Guid>("StepResultId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("StepResultId");

                                    b2.ToTable("retry_attempts", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("StepResultId");
                                });

                            b1.Navigation("RetryHistory");
                        });

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Yukti.Domain.FlowAuthoring.Flow", b =>
                {
                    b.OwnsMany("Yukti.Domain.FlowAuthoring.FlowStep", "Steps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("FlowId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Module")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<string>("Params")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("params");

                            b1.Property<string>("SaveAs")
                                .HasColumnType("text");

                            b1.Property<string>("WhenCondition")
                                .HasColumnType("text")
                                .HasColumnName("when_condition");

                            b1.HasKey("Id");

                            b1.HasIndex("FlowId", "Order")
                                .IsUnique();

                            b1.ToTable("flow_steps", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FlowId");
                        });

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Yukti.Domain.ModulePlugin.ModuleRegistration", b =>
                {
                    b.OwnsMany("Yukti.Domain.ModulePlugin.ModuleActionEntry", "Actions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("ActionName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("DeprecationNotice")
                                .HasColumnType("text");

                            b1.Property<bool>("IsDeprecated")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("ModuleRegistrationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Schema")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("schema");

                            b1.HasKey("Id");

                            b1.HasIndex("ModuleRegistrationId");

                            b1.ToTable("module_action_entries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ModuleRegistrationId");
                        });

                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
